<a href="https://colab.research.google.com/github/Manawariqbal/Data-science-code/blob/main/Naive_Bayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
"""
events =
Toss={HT} 2toss={HH,HT,TH,TT}
Dice={1,2,3,4,5,6}
{1,2,3,4,5,6}
Possibility of even number ={2,4,6}
P(A)=3/6=1/2=0.5

P(number>5)=1/6


Probability=no of fovourable outcome /Total number of outcome


S={H,T}
2 baar={HH,HT,TH,TT}
P(HH)=1/4=0.25


Independent_event=P(H) and P(6)=1/2,1/6
=P(A and B)=P(A)*P(B)
{H-1,2,3,4,5,6
T-1,2,3,4,5,6}
P(H/6)=P(H)*P(6)=1/2*1/6=1/12



Conditional Probability=

Dependent_event=2 keys 1 lock

P(correct_first_time)=1/2


Bag
3 red ball
2 blue ball
Your task is to pick 2 ball without replacement

Firs time pick
P(R1)=3/5
P(R2)=2/4



P(A and B)=P(A)*P(B/A)


P(R1 and R2)=P(R1)*P(R2/R1)=(3/5)*(2/4)=3/10




P(A and B)=P(A)*P(B/A)
P(A and B)=P(B and A)
P(B/A)=P(A and B)/P(A)




P(A/B)=P(A)*P(B/A)/P(B)




P(A and B)=P(A)*P(B/A)

Bayes Theoram=P(A/B)=P(A)*P(B/A)/P(B)



Example=
in a college 100 students
60% Boys =60
40% Girls =40

30% boys play cricket=18

20% girls play cricket =8


we selected a random student and the students plays cricket
Q=What will be the probability that the student is boy
B=Boy
C=cricket


P(Boy/cricket)=P(Boy)*P(Cricket/Boy)/P(cricket)

Given=
          P(Boy)=60/100=0.6
          P(cricket/boy)=30/100=0.3
          P(G)=40/100=0.4
          P(cricket/G)=20/100=0.2

P(cricket)=26/100=0.26

P(Boy/cricket)=0.6*0.3/0.26=0.59






#Spam Email Detection


suppose Total number of emails=100
20% emails are spam =20

80% email are not spam =80



90% spam email contains "winner"=18

5% normal email contains "winner"=4



now we have receive one email which contains the word "winner"

calculate the probability that this email is spam

P(spam/winner)=P(spam)*P(winner/spam)/P(winner)

p(spam)=20/100=0.2
p(winner/spam)=90/100=0.9

p(winner)=22/100=0.22

p(spam/winner)=0.2*0.9/0.22=0.68






"""

In [ ]:
#Types of Naive Bayes Algorithms
"""

1:Gaussian Naive Bayes
Use if features are continues



2:Multinomial Naive Bayes(claassification)
used when features represent the frequency of term

commonly used for
text classification
words count
spam Detection
Document classification


3:Bernoulli Naive Bayes

used when features are binary
"""

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv("/content/loan_approval_dataset.csv")
df.head()

,loan_id,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,1,2,Graduate,No,9600000,29900000,12,778,2400000,17600000,22700000,8000000,Approved
1,2,0,Not Graduate,Yes,4100000,12200000,8,417,2700000,2200000,8800000,3300000,Rejected
2,3,3,Graduate,No,9100000,29700000,20,506,7100000,4500000,33300000,12800000,Rejected
3,4,3,Graduate,No,8200000,30700000,8,467,18200000,3300000,23300000,7900000,Rejected
4,5,5,Not Graduate,Yes,9800000,24200000,20,382,12400000,8200000,29400000,5000000,Rejected

In [6]:

df.columns

Index([' no_of_dependents', ' education', ' self_employed', ' income_annum',
       ' loan_amount', ' loan_term', ' cibil_score',
       ' residential_assets_value', ' commercial_assets_value',
       ' luxury_assets_value', ' bank_asset_value', ' loan_status'],
      dtype='object')

In [7]:
df

X=df.drop(' loan_status',axis=1)
y=df[' loan_status']
#

In [9]:
X
y

0        Approved
1        Rejected
2        Rejected
3        Rejected
4        Rejected
          ...
4264     Rejected
4265     Approved
4266     Rejected
4267     Approved
4268     Approved
Name:  loan_status, Length: 4269, dtype: object

In [10]:
#encoding
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
X[' self_employed']=le.fit_transform(X[' self_employed'])
X[' education']=le.fit_transform(X[' education'])

In [11]:
X

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value
0,2,0,0,9600000,29900000,12,778,2400000,17600000,22700000,8000000
1,0,1,1,4100000,12200000,8,417,2700000,2200000,8800000,3300000
2,3,0,0,9100000,29700000,20,506,7100000,4500000,33300000,12800000
3,3,0,0,8200000,30700000,8,467,18200000,3300000,23300000,7900000
4,5,1,1,9800000,24200000,20,382,12400000,8200000,29400000,5000000
...,...,...,...,...,...,...,...,...,...,...,...
4264,5,0,1,1000000,2300000,12,317,2800000,500000,3300000,800000
4265,0,1,1,3300000,11300000,20,559,4200000,2900000,11000000,1900000
4266,2,1,0,6500000,23900000,18,457,1200000,12400000,18100000,7300000
4267,1,1,0,4100000,12800000,8,780,8200000,700000,14100000,5800000
4268,1,0,0,9200000,29700000,10,607,17800000,11800000,35700000,12000000

In [12]:
#train test spillit
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [17]:
from sklearn.naive_bayes import GaussianNB

model = GaussianNB()
model.fit(X_train, y_train)


#predi
y_pred = model.predict(X_test)
#Accuracy
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.7716627634660421